mod 'puppetlabs-apache'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat'
mod 'puppetlabs-yumrepo_core', '1.0.7'
mod 'puppet-nginx'
mod 'saz-timezone', '6.0.0'
mod 'thias-nagios', '2.0.0'
mod 'puppet/r10k', '8.0.0'
mod 'camptocamp/postfix', '1.8.0'
mod 'puppetlabs/puppet_agent', '2.1.2'
mod 'saz/ssh', '6.0.0'
mod 'puppet/cron', '1.3.1'
mod 'puppet/rsyslog', '4.0.0'
mod 'graylog-graylog'
mod 'puppet-mongodb'
mod 'richardc-datacat'
mod 'elastic-elastic_stack'
mod 'elastic-elasticsearch'
